var epaKeywords = [
    "Agriculture",
    "Air",
    "Biology",
    "Boundaries and Base Data",
    "Chemicals",
    "Cleanup",
    "Climate",
    "Climate Change",
    "Compliance",
    "Conservation",
    "Contaminant",
    "Disaster",
    "Drinking Water",
    "Ecological",
    "Ecology",
    "Ecosystem",
    "Emergency",
    "Emergency Response",
    "Energy",
    "Enforcement",
    "Environment",
    "Environmental Justice",
    "Estuary",
    "Exposure",
    "Facilities",
    "Grants",
    "Ground Water",
    "Hazards",
    "Health",
    "Human",
    "Impact",
    "Indicator",
    "Indoor Air",
    "Inspections",
    "Land",
    "Management",
    "Marine",
    "Modeling",
    "Monitoring",
    "Natural Resources",
    "Permits",
    "Pesticides",
    "Quality",
    "Radiation",
    "Recreation",
    "Regulated Facilities",
    "Regulatory",
    "Remediation",
    "Response",
    "Risk",
    "Sites",
    "Spills",
    "Surface Water",
    "Sustainability",
    "Toxics",
    "Transportation",
    "Waste",
    "Water"
  ];
var placeKeywords = [
    "United States",
    "Canada",
    "Mexico",
    "Alaska",
    "Hawaii",
    "Washington DC",
    "American Samoa",
    "Puerto Rico",
    "Virgin Islands",
    "Alabama",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ];
var epaOrganizationNames = {
    "OA": [
      "OA",
      "OA, EAB",
      "OA, IO",
      "OA, OALJ",
      "OA, OCEM",
      "OA, OCEM, CMO",
      "OA, OCEM, CPOS",
      "OA, OCEM, IO",
      "OA, OCEM, PTOS",
      "OA, OCHP",
      "OA, OCHP, IO",
      "OA, OCHPEE, CAHPD",
      "OA, OCHPEE, EED",
      "OA, OCIR",
      "OA, OCIR, IMD",
      "OA, OCIR, IO",
      "OA, OCIR, OCA",
      "OA, OCIR, OIR",
      "OA, OCIR, OIR, IO",
      "OA, OCIR, OIR, NEPPS",
      "OA, OCIR, OIR, SL",
      "OA, OCIR, ORO",
      "OA, OCR",
      "OA, OCR, AEDS",
      "OA, OCR, ECRS",
      "OA, OCR, ECS",
      "OA, OCR, IO",
      "OA, ODA",
      "OA, OEAEE",
      "OA, OEAEE, IO",
      "OA, OEAEE, OLRCP",
      "OA, OEAEE, OMMCT",
      "OA, OEAEE, OMR",
      "OA, OEAEE, OPE",
      "OA, OEAEE, OS",
      "OA, OEAEE, OWC",
      "OA, OES",
      "OA, OEX",
      "OA, OEX, ECS",
      "OA, OEX, IO",
      "OA, OEX, RMOS",
      "OA, OHS",
      "OA, OP",
      "OA, OP, IO",
      "OA, OP, NCEE",
      "OA, OP, NCEE, BAMDD",
      "OA, OP, NCEE, IO",
      "OA, OP, NCEE, RPSD",
      "OA, OP, NCEE, SPAD",
      "OA, OP, ORPM",
      "OA, OP, ORPM, IO",
      "OA, OP, ORPM, PRAD",
      "OA, OP, ORPM, RMD",
      "OA, OP, OSC",
      "OA, OP, OSC, CARD",
      "OA, OP, OSC, CSSDD",
      "OA, OP, OSC, FSD",
      "OA, OP, OSC, IO",
      "OA, OP, OSEM",
      "OA, OP, OSEM, ESD",
      "OA, OP, OSEM, IESD",
      "OA, OP, OSEM, IO",
      "OA, OP, OSEM, PSS",
      "OA, OP, OSEM, SMD",
      "OA, OPEI, ASIS",
      "OA, OPEI, NCEI",
      "OA, OPEI, NCEI, IO",
      "OA, OPEI, NCEI, OBCI",
      "OA, OPEI, NCEI, OEPI",
      "OA, OPEI, RMS",
      "OA, OSBP",
      "OA, OSBP, IO",
      "OA, OSDBU, ODD",
      "OA, SAB",
      "OA, SAB, IO"
    ],
    "OAR": [
      "OAR, OAA",
      "OAR, OAA, CSIPS",
      "OAR, OAA, IO",
      "OAR, OAA, OPAR",
      "OAR, OAA, OPMO",
      "OAR, OAP",
      "OAR, OAP, CAMD",
      "OAR, OAP, CCD",
      "OAR, OAP, CPPD",
      "OAR, OAP, OD",
      "OAR, OAP, SPD",
      "OAR, OAQPS",
      "OAR, OAQPS, AQAD",
      "OAR, OAQPS, AQAD, AAMG",
      "OAR, OAQPS, AQAD, AQAG",
      "OAR, OAQPS, AQAD, AQMG",
      "OAR, OAQPS, AQAD, EIAG",
      "OAR, OAQPS, AQAD, IO",
      "OAR, OAQPS, AQAD, MTG",
      "OAR, OAQPS, AQPD",
      "OAR, OAQPS, AQPD, GSG",
      "OAR, OAQPS, AQPD, IO",
      "OAR, OAQPS, AQPD, NSRG",
      "OAR, OAQPS, AQPD, OPG",
      "OAR, OAQPS, AQPD, SLPG",
      "OAR, OAQPS, CORE",
      "OAR, OAQPS, HEID",
      "OAR, OAQPS, HEID, AEG",
      "OAR, OAQPS, HEID, ASG",
      "OAR, OAQPS, HEID, ATAG",
      "OAR, OAQPS, HEID, CIMG",
      "OAR, OAQPS, HEID, IO",
      "OAR, OAQPS, HEID, RBG",
      "OAR, OAQPS, OD",
      "OAR, OAQPS, OID",
      "OAR, OAQPS, OID, CTPG",
      "OAR, OAQPS, OID, IO",
      "OAR, OAQPS, OID, IPOG",
      "OAR, OAQPS, OID, ITG",
      "OAR, OAQPS, OID, NADG",
      "OAR, OAQPS, OID, RDPAG",
      "OAR, OAQPS, PACS",
      "OAR, OAQPS, SPPD",
      "OAR, OAQPS, SPPD, ESG",
      "OAR, OAQPS, SPPD, FIG",
      "OAR, OAQPS, SPPD, IO",
      "OAR, OAQPS, SPPD, MICG",
      "OAR, OAQPS, SPPD, MMG",
      "OAR, OAQPS, SPPD, MPG",
      "OAR, OAQPS, SPPD, NRG",
      "OAR, OAQPS, SPPD, PSG",
      "OAR, OAQPS, SPPD, RCG",
      "OAR, ORIA",
      "OAR, ORIA, IED",
      "OAR, ORIA, NAREL-MTG",
      "OAR, ORIA, OD",
      "OAR, ORIA, RIENL-LV",
      "OAR, ORIA, RPD",
      "OAR, ORIA, RSD",
      "OAR, OTAQ",
      "OAR, OTAQ, ASD",
      "OAR, OTAQ, ATD",
      "OAR, OTAQ, CD",
      "OAR, OTAQ, OD",
      "OAR, OTAQ, TATD",
      "OAR, OTAQ, TCD",
      "OAR, OTAQ, TRPD"
    ],
    "OARM": [
      "OARM",
      "OARM, OA",
      "OARM, OA, FMSD",
      "OARM, OA, IO",
      "OARM, OA, SHEMD",
      "OARM, OA, SMD",
      "OARM, OAA",
      "OARM, OAA, IO",
      "OARM, OAA, OPRM",
      "OARM, OAM",
      "OARM, OAM, CPOD",
      "OARM, OAM, HPOD",
      "OARM, OAM, IO",
      "OARM, OAM, PTOD",
      "OARM, OAM, RTPPOD",
      "OARM, OAM, SRRPOD",
      "OARM, OARM-CINC",
      "OARM, OARM-CINC, FMSD",
      "OARM, OARM-CINC, HRMD",
      "OARM, OARM-CINC, HRMD-LV",
      "OARM, OARM-CINC, HRMD-LV, IO",
      "OARM, OARM-CINC, IO",
      "OARM, OARM-CINC, IRMD",
      "OARM, OARM-CINC-LV, HRSSC",
      "OARM, OARM-RTP",
      "OARM, OARM-RTP, FMSD",
      "OARM, OARM-RTP, HRMD",
      "OARM, OARM-RTP, IO",
      "OARM, OARM-RTP, IRMD",
      "OARM, OGD",
      "OARM, OGD, GIAMD",
      "OARM, OGD, IO",
      "OARM, OGD, SDD",
      "OARM, OHR, EDSD",
      "OARM, OHR, ERD",
      "OARM, OHR, HCMD",
      "OARM, OHR, HQOPERS",
      "OARM, OHR, HRPD",
      "OARM, OHR, IO, PMT, LERS",
      "OARM, OHR, ITD"
    ],
    "OCFO": [
      "OCFO",
      "OCFO, CEF",
      "OCFO, IO",
      "OCFO, OB",
      "OCFO, OB, FCPS",
      "OCFO, OB, IO",
      "OCFO, OB, MMAS",
      "OCFO, OB, RPROS",
      "OCFO, OB, SIMS",
      "OCFO, OB, TFAAS",
      "OCFO, OC",
      "OCFO, OC, APBD",
      "OCFO, OC, FMD",
      "OCFO, OC, FSD",
      "OCFO, OC, IO",
      "OCFO, OC, SPIS",
      "OCFO, OETI",
      "OCFO, OETI, BDSS",
      "OCFO, OETI, IO",
      "OCFO, OETI, SPIS",
      "OCFO, OFM",
      "OCFO, OFM, FPPS",
      "OCFO, OFM, FSS",
      "OCFO, OFM, IO",
      "OCFO, OFM, PCS",
      "OCFO, OFM, RAS",
      "OCFO, OFM, WCFS",
      "OCFO, OFS",
      "OCFO, OFS, CFC",
      "OCFO, OFS, IO",
      "OCFO, OFS, LVFC",
      "OCFO, OFS, OSS",
      "OCFO, OFS, RFC",
      "OCFO, OPAA",
      "OCFO, OPAA, ACCTBLS",
      "OCFO, OPAA, AS",
      "OCFO, OPAA, BDSS",
      "OCFO, OPAA, IO",
      "OCFO, OPAA, PS",
      "OCFO, ORIM",
      "OCFO, OTS, AMS",
      "OCFO, OTS, BSS",
      "OCFO, OTS, IO",
      "OCFO, OTS, PES",
      "OCFO, OTS, RTP",
      "OCFO, OTS, WRS"
    ],
    "OCSPP": [
      "OCSPP",
      "OCSPP, OAA",
      "OCSPP, OAA, DAA",
      "OCSPP, OAA, IO",
      "OCSPP, OAA, OPMO",
      "OCSPP, OPP",
      "OCSPP, OPP, AD",
      "OCSPP, OPP, BEAD",
      "OCSPP, OPP, BPPD",
      "OCSPP, OPP, EFED",
      "OCSPP, OPP, FEAD",
      "OCSPP, OPP, HED",
      "OCSPP, OPP, IO",
      "OCSPP, OPP, ITRMD",
      "OCSPP, OPP, PRD",
      "OCSPP, OPP, RD",
      "OCSPP, OPPT",
      "OCSPP, OPPT, CCD",
      "OCSPP, OPPT, EAD",
      "OCSPP, OPPT, EETD",
      "OCSPP, OPPT, IMD",
      "OCSPP, OPPT, IO",
      "OCSPP, OPPT, NPCD",
      "OCSPP, OPPT, PPD",
      "OCSPP, OPPT, RAD",
      "OCSPP, OSCP",
      "OCSPP, OSCP, EACPD",
      "OCSPP, OSCP, HACPD",
      "OCSPP, OSCP, IO"
    ],
    "OECA": [
      "OECA",
      "OECA, FFEO",
      "OECA, HSD",
      "OECA, IO",
      "OECA, IO, ARMS",
      "OECA, IO, OEJ",
      "OECA, IO, OPPAC",
      "OECA, OAP, AMD",
      "OECA, OAP, BFMD",
      "OECA, OAP, IO",
      "OECA, OAP, ITD",
      "OECA, OAP, PLCD",
      "OECA, OC",
      "OECA, OC, AD",
      "OECA, OC, CAMPD",
      "OECA, OC, CASPD",
      "OECA, OC, ETDD",
      "OECA, OC, IO",
      "OECA, OC, MAMPD",
      "OECA, OC, NETI",
      "OECA, OCE",
      "OECA, OCE, AED",
      "OECA, OCE, IO",
      "OECA, OCE, RED",
      "OECA, OCE, SLPD",
      "OECA, OCE, TPED",
      "OECA, OCE, WCED",
      "OECA, OCE, WED",
      "OECA, OCEFT",
      "OECA, OCEFT, CID",
      "OECA, OCEFT, HSD",
      "OECA, OCEFT, IO",
      "OECA, OCEFT, LCD",
      "OECA, OCEFT, LCRMD",
      "OECA, OCEFT, NEIC",
      "OECA, OCEFT, RMS",
      "OECA, OFA",
      "OECA, OFA, ICAD",
      "OECA, OFA, IO",
      "OECA, OFA, NCD",
      "OECA, OSRE",
      "OECA, OSRE, IO",
      "OECA, OSRE, PPED",
      "OECA, OSRE, RSD"
    ],
    "OEI": [
      "OEI",
      "OEI, IO",
      "OEI, IO, OPRO",
      "OEI, IO, PTT",
      "OEI, IO, QS",
      "OEI, OIAA",
      "OEI, OIAA, EAD",
      "OEI, OIAA, IAD",
      "OEI, OIAA, IO",
      "OEI, OIAA, TRIPD",
      "OEI, OIC",
      "OEI, OIC, CSTD",
      "OEI, OIC, IESD",
      "OEI, OIC, IO",
      "OEI, OTOP",
      "OEI, OTOP, EDSD",
      "OEI, OTOP, IO",
      "OEI, OTOP, MISD",
      "OEI, OTOP, NCC"
    ],
    "OGC": [
      "OGC, ADRLO",
      "OGC, ARLO",
      "OGC, CCILO",
      "OGC, CRFLO",
      "OGC, DGC",
      "OGC, GLO",
      "OGC, PTSLO",
      "OGC, RMO",
      "OGC, SWERLO",
      "OGC, WLO"
    ],
    "OIG": [
      "OIG",
      "OIG, OA",
      "OIG, OC",
      "OIG, OCIHS",
      "OIG, OCIHS, IO",
      "OIG, OCPM",
      "OIG, OI",
      "OIG, OMS",
      "OIG, OMS, CAPRC",
      "OIG, OMS, CENRC",
      "OIG, OMS, ERC",
      "OIG, OMS, NRC",
      "OIG, OMS, WRC",
      "OIG, OPE"
    ],
    "OITA": [
      "OITA, AIEO",
      "OITA, OGAP",
      "OITA, OMIS",
      "OITA, ORBA"
    ],
    "ORD": [
      "ORD",
      "ORD, NCCT",
      "ORD, NCCT, IO",
      "ORD, NCEA",
      "ORD, NCEA, IO",
      "ORD, NCEA, IRISD",
      "ORD, NCEA, NCEA-CINC",
      "ORD, NCEA, NCEA-RTP",
      "ORD, NCEA, NCEA-WASH",
      "ORD, NCEA, ODD",
      "ORD, NCEA, PSS",
      "ORD, NCEA, RAFS",
      "ORD, NCER",
      "ORD, NCER, ASD",
      "ORD, NCER, HRFD",
      "ORD, NCER, IO",
      "ORD, NCER, IO-DD",
      "ORD, NCER, ODD",
      "ORD, NCER, PRD",
      "ORD, NCER, QAD",
      "ORD, NCER, RSD",
      "ORD, NCER, TED",
      "ORD, NERL",
      "ORD, NERL, AMAD",
      "ORD, NERL, EERD",
      "ORD, NERL, ERD",
      "ORD, NERL, ESD",
      "ORD, NERL, HEASD",
      "ORD, NERL, IO",
      "ORD, NERL, IO-DD",
      "ORD, NERL, MCEARD",
      "ORD, NERL, ODD",
      "ORD, NHEERL",
      "ORD, NHEERL, ADE",
      "ORD, NHEERL, ADH",
      "ORD, NHEERL, AED",
      "ORD, NHEERL, ECD",
      "ORD, NHEERL, EMAP",
      "ORD, NHEERL, EPHD",
      "ORD, NHEERL, ETD",
      "ORD, NHEERL, GED",
      "ORD, NHEERL, HSD",
      "ORD, NHEERL, IO",
      "ORD, NHEERL, ISTD",
      "ORD, NHEERL, MED",
      "ORD, NHEERL, NTD",
      "ORD, NHEERL, POS",
      "ORD, NHEERL, RCU",
      "ORD, NHEERL, RPCS",
      "ORD, NHEERL, RTD",
      "ORD, NHEERL, TAD",
      "ORD, NHEERL, WED",
      "ORD, NHSRC",
      "ORD, NHSRC, DCMD",
      "ORD, NHSRC, IO",
      "ORD, NHSRC, TCAD",
      "ORD, NHSRC, WIPD",
      "ORD, NRMRL",
      "ORD, NRMRL, APPCD",
      "ORD, NRMRL, GWERD",
      "ORD, NRMRL, IO-ETAVO",
      "ORD, NRMRL, IO-IO",
      "ORD, NRMRL, IO-LSAS",
      "ORD, NRMRL, IO-ROS",
      "ORD, NRMRL, IO-TCOS",
      "ORD, NRMRL, LRPCD",
      "ORD, NRMRL, STD",
      "ORD, NRMRL, WSWRD",
      "ORD, OAA, ORMA",
      "ORD, OAA, OSA",
      "ORD, OAA, OSP",
      "ORD, OARS",
      "ORD, OARS, BED",
      "ORD, OARS, EMD",
      "ORD, OARS, HRD",
      "ORD, OARS, IO",
      "ORD, OARS, OPARM",
      "ORD, OARS, TMD",
      "ORD, OSIM",
      "ORD, OSIM, ASD",
      "ORD, OSIM, CSD",
      "ORD, OSIM, EOD",
      "ORD, OSIM, IMSD",
      "ORD, OSIM, IO",
      "ORD, OSIM, PMSD"
    ],
    "OSWER": [
      "OSWER",
      "OSWER, OAA",
      "OSWER, OAA, CEPPO",
      "OSWER, OAA, FFRRO",
      "OSWER, OAA, IPCO",
      "OSWER, OAA, OD",
      "OSWER, OAA, OPM",
      "OSWER, OAA, OSPS",
      "OSWER, OAA, TIO",
      "OSWER, OBLR",
      "OSWER, OEM",
      "OSWER, OEM, BOC",
      "OSWER, OEM, ECD",
      "OSWER, OEM, IO",
      "OSWER, OEM, NDT",
      "OSWER, OEM, NPPD",
      "OSWER, OEM, POCD",
      "OSWER, OEM, RPDD",
      "OSWER, ORCR",
      "OSWER, ORCR, MRWMD",
      "OSWER, ORCR, OD",
      "OSWER, ORCR, PIID",
      "OSWER, ORCR, PMCAO",
      "OSWER, ORCR, RCSD",
      "OSWER, OSRTI",
      "OSWER, OSRTI, ARD",
      "OSWER, OSRTI, ARD, 1-2-6-9-10SB",
      "OSWER, OSRTI, ARD, 3-4-5-7-8SB",
      "OSWER, OSRTI, ARD, CIPIB",
      "OSWER, OSRTI, ARD, CPCMB",
      "OSWER, OSRTI, ARD, IO",
      "OSWER, OSRTI, ARD, SARDB",
      "OSWER, OSRTI, ARD, SPB",
      "OSWER, OSRTI, ARD, STSIB",
      "OSWER, OSRTI, OD",
      "OSWER, OSRTI, RMD",
      "OSWER, OSRTI, RMD, BPB",
      "OSWER, OSRTI, RMD, CMB",
      "OSWER, OSRTI, RMD, HRB",
      "OSWER, OSRTI, RMD, IMB",
      "OSWER, OSRTI, RMD, IO",
      "OSWER, OSRTI, TIFSD",
      "OSWER, OSRTI, TIFSD, ASB",
      "OSWER, OSRTI, TIFSD, ERT",
      "OSWER, OSRTI, TIFSD, IO",
      "OSWER, OSRTI, TIFSD, TAB",
      "OSWER, OSRTI, TIFSD, TIIB",
      "OSWER, OUST",
      "OSWER, OUST, CRD",
      "OSWER, OUST, IO",
      "OSWER, OUST, MCD",
      "OSWER, OUST, RPD"
    ],
    "OW": [
      "OW",
      "OW, NAIEO",
      "OW, OAA",
      "OW, OAA, AIEO",
      "OW, OAA, IO",
      "OW, OGWDW",
      "OW, OGWDW, DWPD",
      "OW, OGWDW, IO",
      "OW, OGWDW, SRMD",
      "OW, OGWDW, WSD",
      "OW, OST",
      "OW, OST, EAD",
      "OW, OST, HECD",
      "OW, OST, IO",
      "OW, OST, SHPD",
      "OW, OWM",
      "OW, OWM, IO",
      "OW, OWM, MSD",
      "OW, OWM, WPD",
      "OW, OWOW",
      "OW, OWOW, AWPD",
      "OW, OWOW, IO",
      "OW, OWOW, OCPD",
      "OW, OWOW, WLD"
    ],
    "REG": [
      "REG 01",
      "REG 01, OARM",
      "REG 01, OEME",
      "REG 01, OEP",
      "REG 01, OES",
      "REG 01, ORA",
      "REG 01, OSRR",
      "REG 02",
      "REG 02, CEPD",
      "REG 02, DECA",
      "REG 02, DEPP",
      "REG 02, DESA",
      "REG 02, ERRD",
      "REG 02, OPM",
      "REG 02, ORA",
      "REG 02, PAD",
      "REG 03",
      "REG 03, APD",
      "REG 03, EAID",
      "REG 03, HSCD",
      "REG 03, LCD",
      "REG 03, ORA",
      "REG 03, PM",
      "REG 03, WPD",
      "REG 04",
      "REG 04, APTMD",
      "REG 04, OEA",
      "REG 04, OPM",
      "REG 04, ORA",
      "REG 04, RCRA",
      "REG 04, SESD",
      "REG 04, SUPERFUND",
      "REG 04, WMD",
      "REG 04, WPD",
      "REG 05",
      "REG 05, ARD",
      "REG 05, LCD",
      "REG 05, ORA",
      "REG 05, OSEC",
      "REG 05, RMD",
      "REG 05, SFD",
      "REG 05, WD",
      "REG 06",
      "REG 06, BOO",
      "REG 06, CAED",
      "REG 06, MD",
      "REG 06, MPPD",
      "REG 06, OEA",
      "REG 06, ORA",
      "REG 06, ORC",
      "REG 06, SD",
      "REG 06, WQPD",
      "REG 07",
      "REG 07, AWMD",
      "REG 07, ESD",
      "REG 07, ORA",
      "REG 07, PM",
      "REG 07, SD",
      "REG 07, WWPD",
      "REG 08",
      "REG 08, OECEJ",
      "REG 08, OEPR",
      "REG 08, OPRA",
      "REG 08, ORA",
      "REG 08, ORA, MO",
      "REG 08, ORA, OCPI",
      "REG 08, ORA, ORC",
      "REG 08, OTMS",
      "REG 09",
      "REG 09, AIR",
      "REG 09, CED",
      "REG 09, MTS",
      "REG 09, ORA",
      "REG 09, ORC",
      "REG 09, SFD",
      "REG 09, WST",
      "REG 09, WTR",
      "REG 10",
      "REG 10, ECL",
      "REG 10, OAWT",
      "REG 10, OCE",
      "REG 10, OE",
      "REG 10, OEA",
      "REG 10, OETPA",
      "REG 10, OMP",
      "REG 10, ORC",
      "REG 10, OW"
    ]
  };

module.exports = {
  epaKeywords:epaKeywords,
  placeKeywords:placeKeywords,
  epaOrganizationNames:epaOrganizationNames
};
